name: finack
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  fluentui_system_icons: ^1.1.176
  auto_route: ^4.0.1
  animations: ^2.0.2
  google_fonts: ^3.0.1
  fl_chart: ^0.55.0

  # Utils
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  equatable: ^2.0.3
  get_it: ^7.2.0

  # Firebase
  google_sign_in: ^5.4.0
  firebase_analytics: ^9.3.0
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.1
  cloud_firestore: ^3.4.2
  firebase_crashlytics: ^2.8.6

#  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.2
  equatable: ^2.0.3
  auto_route_generator: ^4.0.0
  bloc_test: ^9.0.3

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #